### ISSUE TITLE
Improve the New Focus 8742 example

### ISSUE THREAD

**Issue by kmpeters** [epics-motor/motorNewFocus#6]
Improve the New Focus 8742 example in the newFocusIOC:

* reduce the number of env vars
* create a cmd/iocsh file that can be easily copied to or called from an existing IOC
* use asyn_motor.db instead of basic_asyn_motor.db

**Comment by davecyl** [comment]
Support for cascaded controllers would simplify the hardware setup and eliminate the need for multi network drops. Tracing the commands to the controller I did not see a controller address in the command string, I think it is something like 3> Command, so I could only address 1-4 motors.
